name: Greeting message

on:
  workflow_dispatch:

env:
  my_name: Amirdhesh
  
jobs:
  
  greet:
    runs-on: ubuntu-latest
    env:
      my_name: Gokul c
    environment: workout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: greeting
        run: echo "Hello, Welcome to github action workflow. ${{secrets.my_name}}"
      
  
