name: Greeting message

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  my_name: Amirdhesh
  
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: greeting
        run: echo "Hello, Welcome to github action workflow. ${{env.my_name}}"
      
  
